server:
  port: 9050
spring:
  application:
    name: e-commerce-wallet
  datasource:
    url: jdbc:mysql://192.168.206.128:3306/commerce?useUnicode=true&character Encoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8       # 你的数据库地址
    username: root  # 你的数据库用户名
    password: 123456789   # 你的数据库密码
    #type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.206.128 #r-2zec1x8fklnvti26iqpd.redis.rds.aliyuncs.com  Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 7001 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
eureka:
  client:
    service-url:
      defaultZone: http://192.168.206.128:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
mybatis:
  mapper-locations: classpath*:mapper/*.xml

value:
  zuul-uri: "http://e-commerce-zuul"

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: e-commerce-admin #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000